### ISSUE TITLE
Switch Only work with turn_on_action

### ISSUE THREAD

**Issue by Lukjam** [lucavb/homebridge-esphome-ts#11]
```
switch:
  - platform: template
    name: RF Power Button
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000101010101000101010111'
          protocol:
            pulse_length: 350
          repeat: 10
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000101010101000101010100'
          protocol:
            pulse_length: 350
          repeat: 10
```
That is the code I used for my ESP8266, but only the turn_on_action is send when I deactivate the switch.
