### ISSUE TITLE
Control Effects

### ISSUE THREAD

**Issue by digimatt22** [lucavb/homebridge-esphome-ts#13]
Would it be possible to expose effects for lights that have them enabled?  The setup is a little involved since you have to use an app like Eve or Home+ but right now it appears this plugin doesn't expose the available effects at all.

**Comment by thewavelength** [comment]
Can add to this as soon as effects are added to the ESPHome firmware, the addon just prints the following and ignores the device:

```[esphome] {} undefined```

My effects array looks like this:

```
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - flicker:
      - strobe:
      - addressable_scan:
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
      - addressable_fireworks:
```
