### ISSUE TITLE
Issue when switching on a lamp

### ISSUE THREAD

**Issue by ream88** [lucavb/homebridge-esphome-ts#15]
I get the following issue in Homebridge's logs when I switch on a lamp in the Home.app: 

```
[9/20/2020, 12:12:08 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at On.<anonymous> (/homebridge/node_modules/homebridge-esphome-ts/dist/homebridgeAccessories/switch.js:17:9)
    at On.emit (events.js:228:7)
    at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
    at HAPServer.emit (events.js:223:5)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)```

**Comment by lucavb** [comment]
Hey, is this happening consistently for you or only every now and then?

**Comment by ream88** [comment]
Every time I switch on or off the lights. Homebridge crashes and reboots afterwards.

**Comment by lucavb** [comment]
Puh, the code there kind of seems rock solid. Would you mind sharing your configuration for the espdevice (please omit sensitive pieces of information) and what version of esphome / of the plugin and homebridge you are using.

**Comment by lucavb** [comment]
Can you try and unpack this file and then install it with `npm i -g homebridge-esphome-ts-1.0.1.tgz`. It is basically version 1.0.1 but with two additional log statements in the switch setup method. 

[homebridge-esphome-ts-1.0.1.tgz.zip](https://github.com/lucavb/homebridge-esphome-ts/files/5252457/homebridge-esphome-ts-1.0.1.tgz.zip)

**Comment by ream88** [comment]
I will have some spare time this evening, hopefully I can test this then! Thx a lot btw for this quick support! 😊

**Comment by ream88** [comment]
This version does indeed work, and nothing interesting in the logs (imho):

```
[9/23/2020, 9:42:03 AM] [esphome] Sonoff Basic Button must be a new accessory undefined
[9/23/2020, 9:42:03 AM] [esphome] Sonoff Basic Button could not be mapped to HomeKit. Please file an issue on Github.
[9/23/2020, 9:42:03 AM] [esphome] Sonoff Lamp must be a new accessory undefined
now setting up a switch Sonoff Lamp Sonoff Lamp
[9/23/2020, 9:42:03 AM] [esphome] Sonoff Lamp discovered and setup.
[9/23/2020, 9:42:03 AM] [esphome] {
  sonoff_basic_button: BinarySensorComponent {
    listEntity: {
      objectId: 'sonoff_basic_button',
      key: 3952376204,
      name: 'Sonoff Basic Button',
      uniqueId: 'sonoffbinary_sensorsonoff_basic_button'
    },
    commandInterface: { send: [Function: send] },
    commandInPipeline: BehaviorSubject {
      _isScalar: false,
      observers: [Array],
      closed: false,
      isStopped: false,
      hasError: false,
      thrownError: null,
      _value: false
    },
    subscriptions: Subscription {
      closed: false,
      _parentOrParents: null,
      _subscriptions: [Array]
    },
    'state$': Observable {
      _isScalar: false,
      source: [Observable],
      operator: [DoOperator]
    },
    state: { key: 3952376204 }
  },
  sonoff_lamp: SwitchComponent {
    listEntity: {
      objectId: 'sonoff_lamp',
      key: 3159477543,
      name: 'Sonoff Lamp',
      uniqueId: 'sonoffswitchsonoff_lamp'
    },
    commandInterface: Connection {
      host: '10.0.0.24',
      port: 6053,
      subscription: [Subscription],
      socket: [Socket],
      'connected$': [Observable],
      'data$': [Observable]
    },
    commandInPipeline: BehaviorSubject {
      _isScalar: false,
      observers: [Array],
      closed: false,
      isStopped: false,
      hasError: false,
      thrownError: null,
      _value: false
    },
    subscriptions: Subscription {
      closed: false,
      _parentOrParents: null,
      _subscriptions: [Array]
    },
    'state$': Observable {
      _isScalar: false,
      source: [Observable],
      operator: [DoOperator]
    },
    state: { key: 3159477543, state: true }
  }
} undefined
set request for Sonoff Lamp. 
set request for Sonoff Lamp. 
set request for Sonoff Lamp. 
set request for Sonoff Lamp.
```

**Comment by ream88** [comment]
And now the released 1.0.1 works as well, super weird!

**Comment by ream88** [comment]
Ok now I got the error again, it looks like it happens when I have two identical Sonoff Basic switches configured.
Both switches use the [basic Sonoff example](https://esphome.io/devices/sonoff_basic.html). Could this be the problem? Do I need to use different config files for each one?

```yaml
<<: !include ./secrets.yml

esphome:
  name: sonoff
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

# wifi is in secrets.yml

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Lamp"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: true
```
