### ISSUE TITLE
Not working with Homebridge

### ISSUE THREAD

**Issue by mmichon** [lucavb/homebridge-esphome-ts#16]
I'm getting the following error in the Homebridge logs:
```
[10/1/2020, 06:33:45] [esphome] Proximity_Sensor must be a new accessory undefined
[10/1/2020, 06:33:45] [esphome] Proximity_Sensor could not be mapped to HomeKit. Please file an issue on Github.
[10/1/2020, 06:33:45] [esphome] {
  proximity_sensor: BinarySensorComponent {
    listEntity: {
      objectId: 'proximity_sensor',
      key: 2368962953,
      name: 'Proximity_Sensor',
      uniqueId: 'controllerbinary_sensorproximity_sensor'
    },
    commandInterface: { send: [Function: send] },
    commandInPipeline: BehaviorSubject {
      _isScalar: false,
      observers: [Array],
      closed: false,
      isStopped: false,
      hasError: false,
      thrownError: null,
      _value: false
    },
    subscriptions: Subscription {
      closed: false,
      _parentOrParents: null,
      _subscriptions: [Array]
    },
    'state$': Observable {
      _isScalar: false,
      source: [Observable],
      operator: [DoOperator]
    }
  }
} undefined
```
Homebridge config:
```json
        {
            "devices": [
                {
                    "host": "controller.local"
                }
            ],
            "debug": true,
            "platform": "esphome"
        }
```

esphome yaml is:
```yaml
esphome:
  name: controller
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "foo"
  password: "bar"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Controller Fallback Hotspot"
    password: "qux"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    name: "Proximity_Sensor"
    pin:
      number: 25
      inverted: False
      mode: INPUT_PULLUP
```

Seems like Homebridge is connecting to the esphome API through homebridge-esphome-ts fine though:
`[22:33:45][D][api.connection:604]: Client 'esphome-ts (192.168.86.216)' connected successfully!`

The binary sensor logic in esphome also has been tested and works.

homebridge-esphome-ts version=1.0.1
Homebridge version=1.1.6
esphome version=1.15.2
