### ISSUE TITLE
Server-side button state change not shown in Homekit

### ISSUE THREAD

**Issue by mmichon** [lucavb/homebridge-esphome-ts#17]
I have a momentary button I want to push for 4 seconds with Homebridge. My config is
```yaml
switch:
  - platform: gpio
    pin: 4
    restore_mode: ALWAYS_OFF
    id: gate_buzzer
  - platform: template
    name: "Gate Buzzer"
    icon: "mdi:gate"
    assumed_state: true
    turn_on_action:
    - switch.turn_on: gate_buzzer
    - delay: 4000ms
    - switch.turn_off: gate_buzzer
    on_turn_off:
    - switch.template.publish:
        id: gate_buzzer
        state: false
```

Pushing the associated switch button in Homebridge does the right thing with the hardware attached to the ESP32 and it turns the Homebridge switch button state ON as expected. 

4 seconds later the ESP32 echoes back that it published the button's state to OFF:
```
[19:55:01][D][switch:021]: 'Gate Buzzer' Turning ON.
[19:55:01][D][switch:021]: 'gate_buzzer' Turning ON.
[19:55:01][D][switch:045]: 'gate_buzzer': Sending state ON
[19:55:05][D][switch:025]: 'gate_buzzer' Turning OFF.
[19:55:05][D][switch:045]: 'gate_buzzer': Sending state OFF`
```
but the switch button in Homebridge is not updated (it remains ON). I have to manually reset the switch button state to OFF before I can use it again. I've tried a number of different options for publishing the state, including lambdas, but nothing seems to reset the Homebridge button state to match that of esphome.
