### ISSUE TITLE
Lights debug as accessory undefined

### ISSUE THREAD

**Issue by Garreth2013** [lucavb/homebridge-esphome-ts#33]
Im currently using Homeassistant, but want to add homebridge. 
Ive got about 35 lights to add, most are added fine. However some are not and debug throws accessory undefined. 
Your assistance here would be greatly appreciated. 

[1/9/2021, 5:30:30 PM] [esphome] panic must be a new accessory undefined
[1/9/2021, 5:30:30 PM] [esphome] panic could not be mapped to HomeKit. Please file an issue on Github.
[1/9/2021, 5:30:30 PM] [esphome] mainbedroom must be a new accessory undefined
[1/9/2021, 5:30:30 PM] [esphome] mainbedroom could not be mapped to HomeKit. Please file an issue on Github.
[1/9/2021, 5:30:30 PM] [esphome] upstairspattio must be a new accessory undefined
[1/9/2021, 5:30:30 PM] [esphome] upstairspattio could not be mapped to HomeKit. Please file an issue on Github.
[1/9/2021, 5:30:30 PM] [esphome] 
```
{
  panic: BinarySensorComponent {
    listEntity: {
      objectId: 'panic',
      key: 3130232582,
      name: 'panic',
      uniqueId: 'mainbedroombinary_sensorpanic'
    },
    commandInterface: { send: [Function: send] },
    commandInPipeline: BehaviorSubject {
      _isScalar: false,
      observers: [Array],
      closed: false,
      isStopped: false,
      hasError: false,
      thrownError: null,
      _value: false
    },
    subscriptions: Subscription {
      closed: false,
      _parentOrParents: null,
      _subscriptions: [Array]
    },
    'state$': Observable {
      _isScalar: false,
      source: [Observable],
      operator: [DoOperator]
    },
    state: { key: 3130232582 }
  },
  mainbedroom: BinarySensorComponent {
    listEntity: {
      objectId: 'mainbedroom',
      key: 2819021838,
      name: 'mainbedroom',
      uniqueId: 'mainbedroombinary_sensormainbedroom'
    },
    commandInterface: { send: [Function: send] },
    commandInPipeline: BehaviorSubject {
      _isScalar: false,
      observers: [Array],
      closed: false,
      isStopped: false,
      hasError: false,
      thrownError: null,
      _value: false
    },
    subscriptions: Subscription {
      closed: false,
      _parentOrParents: null,
      _subscriptions: [Array]
    },
    'state$': Observable {
      _isScalar: false,
      source: [Observable],
      operator: [DoOperator]
    },
    state: { key: 2819021838 }
  },
  upstairspattio: BinarySensorComponent {
    listEntity: {
      objectId: 'upstairspattio',
      key: 2644448661,
      name: 'upstairspattio',
      uniqueId: 'mainbedroombinary_sensorupstairspattio'
    },
    commandInterface: { send: [Function: send] },
    commandInPipeline: BehaviorSubject {
      _isScalar: false,
      observers: [Array],
      closed: false,
      isStopped: false,
      hasError: false,
      thrownError: null,
      _value: false
    },
    subscriptions: Subscription {
      closed: false,
      _parentOrParents: null,
      _subscriptions: [Array]
    },
    'state$': Observable {
      _isScalar: false,
      source: [Observable],
      operator: [DoOperator]
    },
    state: { key: 2644448661 }
  }
} undefined
```

```
esphome:
  name: mainbedroom
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "Harveys Wi-Fi Network"
  password: "Damionos4016"
  ap:
    ssid: "GMainbedroom Fallback Hotspot"
    password: "omitted"
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "panic"
    on_press:
      then:
        - light.toggle: panic
        
        
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "mainbedroom"
    on_press:
      then:
        - light.toggle: mainbedroom
        
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "upstairspattio"
    on_press:
      then:
        - light.toggle: upstairspattio
        

light:
  - platform: binary
    name: "panic"
    id: panic
    output: panic_relay

  - platform: binary
    name: "mainbedroom"
    id: mainbedroom
    output: mainbedroom_relay

  - platform: binary
    name: "upstairspattio"
    id: upstairspattio
    output: upstairspattio_relay
    
output:

  - platform: gpio
    id: panic_relay
    pin: GPIO12
  - platform: gpio
    id: mainbedroom_relay
    pin: GPIO05
  - platform: gpio
    id: upstairspattio_relay
    pin: GPIO04
```
