### ISSUE TITLE
Unable to add accessory: "must be a new accessory []"

### ISSUE THREAD

**Issue by JohnFodero** [lucavb/homebridge-esphome-ts#357]
Attempting to add my first ESPHome accessory to homebridge (v1.4.1) with homebridge-esphome-ts (v1.5.1).
Logs show the plugin connects to the device, however no switch device is added to HomeKit. 

ESPHome Device Log
``` 
[21:46:41][D][api:102]: Accepted ::FFFF:C0A8:3292
[21:46:41][D][api.connection:861]: esphome-ts (::FFFF:C0A8:3292): Connected successfully
```
ESPHome Device Config
```
esphome:
  name: seebee

esp32:
  board: lolin32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "xxxxx"
  password: "xxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xxxxxxxx"
    password: "xxxxxxxx"

switch:
  - platform: gpio
    name: "StringLightSwitch"
    pin: 5
    restore_mode: ALWAYS_OFF


captive_portal:
```
Homebridge Plugin Config 
```
{
    "devices": [
        {
            "host": "seebee.local",
            "port": 6053
        }
    ],
    "debug": true,
    "discover": true,
    "platform": "esphome"
}

```
Homebridge Log
```
[8/21/2022, 5:31:08 PM] [esphome] HAP Device discovered seebee
[8/21/2022, 5:31:08 PM] [esphome] Writing the raw data from your ESP Device to /tmp
[8/21/2022, 5:31:08 PM] [esphome]  must be a new accessory []
timeout
```

Plugin Debug Logs (at `/tmp`)
```
{"type":2,"payload":"CAEQBhoac2VlYmVlIChlc3Bob21lIHYyMDIyLjguMCkiBnNlZWJlZQ==","time":1661118401412}
{"type":4,"payload":"","time":1661118401434}
{"type":10,"payload":"EgZzZWViZWUaEUFDOjY3OkIyOjMzOkZGOkVDIggyMDIyLjguMCoVQXVnIDIxIDIwMjIsIDIxOjQyOjM2Mgdsb2xpbjMy","time":1661118401456}
{"type":17,"payload":"","time":1661118401491}
{"type":26,"payload":"","time":1661118401534}
{"type":19,"payload":"","time":1661118401625}
{"type":7,"payload":"","time":1661118461516}
{"type":7,"payload":"","time":1661118521547}
{"type":7,"payload":"","time":1661118581574}
{"type":7,"payload":"","time":1661118641595}
{"type":7,"payload":"","time":1661118701626}
{"type":7,"payload":"","time":1661118761648}
```
