### ISSUE TITLE
Support for API encryption

### ISSUE THREAD

**Issue by runestone74** [lucavb/homebridge-esphome-ts#506]
Hi, the standard ESP Home config is using API encryption for Home Assistant support. Is this supported as well? I only found info for password.

```
# Enable Home Assistant API
api:
  encryption:
    key: "qWHsO5CS0tz2Y4ZGYMicOAyFGIrWlu3wVHm8HTEIBms="
```
