### ISSUE TITLE
RangeError: index out of range: 18 + 32 > 35

### ISSUE THREAD

**Issue by Veldkornet** [lucavb/homebridge-esphome-ts#64]
Using HomeBridge 1.3.2, I added just 1 device, using only the device IP address or name, and HomeBridge crashes with the below error.

Config:
```
        {
            "devices": [
                {
                    "host": "doorbell.local"
                }
            ],
            "debug": true,
            "platform": "esphome"
        }
```

Logs:
```
[3/6/2021, 2:15:05 PM] RangeError: index out of range: 18 + 32 > 35
    at indexOutOfRange (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:13:12)
    at Reader.skip (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:338:19)
    at Reader.skipType (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:364:18)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/protobuf/api.js:1959:28)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/client.js:10:20)
    at Object.stateParser (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/helpers.js:24:29)
    at MapSubscriber.project (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/espDevice.js:23:148)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:84:29)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at SimpleInnerSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/innerSubscribe.ts:30:17)
    at SimpleInnerSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Observable._subscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
    at Observable._trySubscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Observable.ts:238:19)
[3/6/2021, 2:15:05 PM] RangeError: index out of range: 18 + 32 > 35
    at indexOutOfRange (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:13:12)
    at Reader.skip (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:338:19)
    at Reader.skipType (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:364:18)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/protobuf/api.js:1959:28)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/client.js:10:20)
    at Object.stateParser (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/helpers.js:24:29)
    at MapSubscriber.project (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/espDevice.js:23:148)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:84:29)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at SimpleInnerSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/innerSubscribe.ts:30:17)
    at SimpleInnerSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Observable._subscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
    at Observable._trySubscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Observable.ts:238:19)
[3/6/2021, 2:15:05 PM] RangeError: index out of range: 18 + 32 > 35
    at indexOutOfRange (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:13:12)
    at Reader.skip (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:338:19)
    at Reader.skipType (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:364:18)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/protobuf/api.js:1959:28)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/client.js:10:20)
    at Object.stateParser (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/helpers.js:24:29)
    at MapSubscriber.project (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/espDevice.js:23:148)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:84:29)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at SimpleInnerSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/innerSubscribe.ts:30:17)
    at SimpleInnerSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Observable._subscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
    at Observable._trySubscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Observable.ts:238:19)
[3/6/2021, 2:15:05 PM] Got SIGTERM, shutting down Homebridge...
[3/6/2021, 2:15:05 PM] RangeError: index out of range: 18 + 32 > 35
    at indexOutOfRange (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:13:12)
    at Reader.skip (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:338:19)
    at Reader.skipType (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:364:18)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/protobuf/api.js:1959:28)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/client.js:10:20)
    at Object.stateParser (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/helpers.js:24:29)
    at MapSubscriber.project (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/espDevice.js:23:148)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:84:29)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at SimpleInnerSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/innerSubscribe.ts:30:17)
    at SimpleInnerSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Observable._subscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
    at Observable._trySubscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Observable.ts:238:19)
[3/6/2021, 2:15:05 PM] RangeError: index out of range: 18 + 32 > 35
    at indexOutOfRange (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:13:12)
    at Reader.skip (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:338:19)
    at Reader.skipType (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:364:18)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/protobuf/api.js:1959:28)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/client.js:10:20)
    at Object.stateParser (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/helpers.js:24:29)
    at MapSubscriber.project (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/espDevice.js:23:148)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:84:29)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at SimpleInnerSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/innerSubscribe.ts:30:17)
    at SimpleInnerSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Observable._subscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
    at Observable._trySubscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Observable.ts:238:19)
[3/6/2021, 2:15:05 PM] RangeError: index out of range: 18 + 32 > 35
    at indexOutOfRange (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:13:12)
    at Reader.skip (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:338:19)
    at Reader.skipType (/homebridge/node_modules/homebridge-esphome-ts/node_modules/protobufjs/src/reader.js:364:18)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/protobuf/api.js:1959:28)
    at Object.decode (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/client.js:10:20)
    at Object.stateParser (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/helpers.js:24:29)
    at MapSubscriber.project (/homebridge/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/espDevice.js:23:148)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:84:29)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at MapSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/map.ts:89:22)
    at MapSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at SwitchMapSubscriber.notifyNext (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/operators/switchMap.ts:166:24)
    at SimpleInnerSubscriber._next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/innerSubscribe.ts:30:17)
    at SimpleInnerSubscriber.Subscriber.next (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Observable._subscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
    at Observable._trySubscribe (/homebridge/node_modules/homebridge-esphome-ts/node_modules/rxjs/src/internal/Observable.ts:238:19)
```

**Comment by Veldkornet** [comment]
I will say that it does seem to add the device and its entities

**Comment by lucavb** [comment]
Interesting. Care to post your device config and the output of `esphome version`

__Please make sure not to post any passwords__

**Comment by Veldkornet** [comment]
Here you go:

ESPHome Version 1.16.2

```
esphome:
  name: doorbell
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorbell Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Doorbell ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Doorbell IP
    ssid:
      name: Doorbell SSID
    bssid:
      name: Doorbell BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Doorbell Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Doorbell WiFi Signal
    update_interval: 60s

# Global to store the on/off state of the chime
globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: 'true'

# Exposed switches.
switch:
  # Switch to restart the doorbell.
  - platform: restart
    name: Doorbell Restart

  # Switch to turn on/off the chime.
  - platform: gpio
    id: relay
    inverted: true
    name: Doorbell Chime
    pin: GPIO0

  # Switch to turn on/off chime when
  # doorbell button is pushed.
  #
  # It creates a "virtual" switch based
  # on a global variable.
  - platform: template
    name: Doorbell Chime Active
    id: chime_active
    restore_state: false
    turn_on_action:
      - globals.set:
          id: chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: chime
          value: 'false'
    lambda: |-
      return id(chime);
# Binary sensor representing the
# Doorbell button push.
binary_sensor:
  - platform: gpio
    id: button
    name: Doorbell Button
    pin:
      # Connected to GPIO on the ESP-01S.
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    filters:
      # Small filter, to debounce the button press.
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      # Only turn on the chime when it is active.
      then:
        if:
          condition:
            - switch.is_on: chime_active
          then:
            - switch.turn_on: relay
    on_release:
      # On release, turn of the chime.
      - switch.turn_off: relay
```
